### ISSUE TITLE
feat: dynamically set preview titles to name of page + rollkit

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#228]
The titles should show up as they do in the titles of the pages on the web browser. As an example:

https://rollkit.dev/tutorials/gm-world = "GM World rollup"

currently, the og preview title is "Rollkit"

is it possible to use this format: "GM World rollup | Rollkit" without displaying "Rollkit | Rollkit" on the home page? and to have the same format for the og description?

**Comment by jcstein** [comment]
i think that you'll know the answer to this. do you know if i made an error in the config that is causing this @brc-dd?

**Comment by brc-dd** [comment]
Ah, not sure if I understood your issue properly, but you probably need to set `titleTemplate: ':title'` in your home page to render just `Rollkit` there. For `og:title`, if you want it dynamic, you need to inject it via `transformPageData` or `transformHead` hooks instead of having a static entry in head.

**Comment by jcstein** [comment]
for homepage, tried `titleTemplate: ':title'` but it renders `Rollkit | Rollkit` still

more important issue here is the `og:title` - do you have an example you could point me to? thanks for the help here

**Comment by jcstein** [comment]
![omg](https://media4.giphy.com/media/8Xo1xoYf4VIydSFHLp/200w.webp)

thank you!
