### ISSUE TITLE
GM World tutorial assumes you are a Mac user

### ISSUE THREAD

**Issue by smuu** [rollkit/docs#96]
https://rollkit.dev/docs/tutorials/gm-world/#install-homebrew

When following the tutorial step by step, you need to install homebrew for Mac, which is not required when using Linux or Windows.
It would be nice to have a toggle to choose the operating system I use and then see the needed commands for my system.

**Comment by jcstein** [comment]
good suggestion, thanks @smuu

i added tabs to the "Setup" section for Linux and Mac. AFAIK, we do not and have not tested on Windows, which is why both Celestia and Rollkit docs only have instructions for Linux and Mac

accidentally pushed to main and it's live... 80417567a55c10793169269b84cb25903b29117b
